### ISSUE TITLE
Tag support?

### ISSUE THREAD

**Issue by digitalsadhu** [eik-lib/issues#13]
We are wanting to automate publishing of our modules to main and also potentially "next" or "beta" branches. NPM supports this but often we want to be able to publish a version of our packages to Eik as well and it's unclear what the best way to handle a "next" version of a package is in terms of publishing to Eik? Could we add support to Eik for tags that basically works in the same way as it does in NPM?

cc/ @trygve-lie @benja

**Comment by trygve-lie** [comment]
Currently Eik should be able to handle `next`, `beta` etc releases. Eik is fully semver compliant and is using the same modules to parse package names and semver versions as NPM so its fully possible to publish a `1.2.1-next.1` version.

Though, In terms of Eik this does not mean anything. For Eik its just a version in terms of being part of a URL so it has no specific function. This should work fine with automatically publishing versions to Eik also.

What would tag support in Eik imply?

**Comment by digitalsadhu** [comment]
Ah! Then we might be fine as is then.

Last time I checked, it wasn’t possible to publish a lower version of a package. Ie. once you publish version 1.1.1, it will never be possible to go back and publish 1.1.0. 
wondering how this will work if we say publish 1.1.2 and then 2.0.0-next.1 and then go back and try to publish 1.1.3?

**Comment by trygve-lie** [comment]
The restriction on publishing higher versions are within the major range. In other words; one should be able to publish a 1.1.4 version, then publish a 2.1.3 version and then go back and publish a 1.1.5 version because these are two different major versions. If we're not able to do so, we have a bug.

Here is btw the logic for comparing pre-releases we're using: https://github.com/npm/node-semver#prerelease-tags

**Comment by digitalsadhu** [comment]
ah, if that's the case then we should be gtg
